// Specs and tasting notes are from Stories Brewery & Kitchen (BTM), which
// supplies the pours. Styles/availability can vary by season.
export const POURS = [
  {
    id: "wheat-ipa",
    beer: "#E7B547",
    name: "Wheat IPA",
    style: "Wheat • India Pale Ale",
    note: "Wheat smoothness against an intense hop finish, with a tropical, fruity kick.",
    abv: "6.0%",
    ibu: "20",
  },
  {
    id: "jammu-witbier",
    beer: "#C2557B",
    name: "Jammu Witbier",
    style: "Belgian-style Witbier",
    note: "Brewed with real jammu, subtly sweet and aromatic, finishing tart and refreshing.",
    abv: "5.3%",
    ibu: "12",
  },
  {
    id: "hefeweizen",
    beer: "#E2A93F",
    img: "/photos/beers/hefeweizen.webp",
    imgFull: "/photos/beers/hefeweizen-full.webp",
    name: "Stories Hefeweizen",
    style: "German Hefeweizen",
    note: "Banana and phenolic clove. A classic German wheat, sessionable and easy.",
    abv: "5.0%",
    ibu: "18",
  },
  {
    id: "apple-cider",
    beer: "#F0D479",
    name: "Apple Cider",
    style: "Cider",
    note: "Crisp, sweet and bursting with apple. No bitterness, just light and lively.",
    abv: "4.0%",
    ibu: "0",
  },
  {
    id: "mango-cider",
    beer: "#F2B93F",
    img: "/photos/beers/mango-cider.webp",
    imgFull: "/photos/beers/mango-cider-full.webp",
    name: "Mango Cider",
    style: "Cider",
    note: "Lush mango sweetness with a bright, tropical feel. Juicy and rooftop-ready.",
    abv: "4.0%",
    ibu: "0",
  },
  {
    id: "belgian-wit",
    beer: "#F3D470",
    img: "/photos/beers/belgian-wit.webp",
    imgFull: "/photos/beers/belgian-wit-full.webp",
    name: "Belgian Wit",
    style: "Belgian Witbier",
    note: "Traditional Belgian wheat with orange peel and coriander. Citrusy and spiced.",
    abv: "5.0%",
    ibu: "12",
  },
  {
    id: "triple-wit",
    beer: "#EDBE55",
    name: "Triple Wit",
    style: "Strong Wheat Ale",
    note: "The classic German wheat dialled up, banana and clove with more intensity and richness.",
    abv: "7.0%",
    ibu: "18",
  },
  {
    id: "kolsch",
    beer: "#F2DD8A",
    img: "/photos/beers/kolsch.webp",
    imgFull: "/photos/beers/kolsch-full.webp",
    name: "Kölsch",
    style: "Kölsch",
    note: "Lager finesse, ale fruitiness. Pale straw, delicate head, clean and snappy finish.",
    abv: "4.7%",
    ibu: "14",
  },
];
